# Generated by Django 6.0 on 2026-02-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='point_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
