# Generated by Django 6.0 on 2026-02-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_point_awarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='point_awarded',
            new_name='resolved_point_awarded',
        ),
        migrations.AddField(
            model_name='issue',
            name='verified_point_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
