# Generated by Django 6.0 on 2026-05-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Document_image',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
    ]
