# Generated by Django 6.0 on 2026-05-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='broadcasts/'),
        ),
    ]
